<style>
.report-head{display:flex;justify-content:space-between;align-items:flex-end;gap:18px;margin-bottom:22px}.report-title{font-size:27px;font-weight:800;letter-spacing:-.03em;margin:0}.report-sub{margin:6px 0 0;color:var(--muted);font-size:13px}.report-date{font-size:12px;color:var(--muted);padding:9px 12px;border:1px solid var(--border);border-radius:10px;background:var(--card)}.report-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.report-kpi{position:relative;padding:18px;border:1px solid var(--border);border-radius:16px;background:var(--card);box-shadow:0 8px 24px rgba(25,34,52,.04);overflow:hidden}.report-kpi:after{content:'';position:absolute;right:-18px;bottom:-22px;width:72px;height:72px;border-radius:50%;background:#f0f3ff}.report-icon{width:38px;height:38px;border-radius:11px;display:grid;place-items:center;margin-bottom:14px;position:relative;z-index:1}.report-kpi-label{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em}.report-kpi-value{font-size:25px;font-weight:800;margin-top:3px;position:relative;z-index:1}.report-grid{display:grid;grid-template-columns:1.25fr .9fr;gap:18px}.report-panel{border:1px solid var(--border);border-radius:16px;background:var(--card);box-shadow:0 8px 24px rgba(25,34,52,.035);overflow:hidden}.report-panel-head{padding:16px 18px;border-bottom:1px solid var(--border);display:flex;justify-content:space-between;align-items:center}.report-panel-title{font-size:14px;font-weight:800}.report-panel-note{font-size:11px;color:var(--muted);margin-top:2px}.category-row{display:flex;align-items:center;justify-content:space-between;padding:13px 18px;border-bottom:1px solid var(--border)}.category-row:last-child{border-bottom:0}.category-left{display:flex;align-items:center;gap:10px}.category-icon{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:#edf2ff;color:#4361ee}.category-name{font-size:12.5px;font-weight:700}.category-count{font-size:11px;color:var(--muted)}.health-box{padding:16px 18px}.health-line{display:flex;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid var(--border);font-size:12px}.health-line:last-child{border-bottom:0}.health-line strong{font-size:13px}.health-status{font-size:10px;font-weight:700;border-radius:999px;padding:5px 8px}.status-good{background:#e9f9f1;color:#16845d}.status-warn{background:#fff4dc;color:#b77900}.status-danger{background:#feecef;color:#c93b58}.report-foot{margin-top:18px;padding:15px 18px;border-radius:15px;background:linear-gradient(135deg,#101827,#1e2a45);color:#f6f8ff;display:flex;justify-content:space-between;align-items:center;gap:16px}.report-foot strong{font-size:13px}.report-foot span{color:#b6c0d2;font-size:11px}.theme-dark .report-kpi:after{background:#202944}.theme-dark .report-foot{background:linear-gradient(135deg,#0d1524,#172238)}
@media(max-width:900px){.report-kpis{grid-template-columns:repeat(2,1fr)}.report-grid{grid-template-columns:1fr}}@media(max-width:600px){.report-head{align-items:flex-start;flex-direction:column}.report-kpis{grid-template-columns:1fr}}
</style>
<div class="report-head"><div><h1 class="report-title">Reports</h1><p class="report-sub">A clean operating view of catalog, stock and customer activity.</p></div><div class="report-date"><i class="fa-regular fa-calendar me-1"></i><?= date('d M Y') ?></div></div>
<div class="report-kpis">
  <div class="report-kpi"><div class="report-icon" style="background:#edf2ff;color:#4361ee"><i class="fa-solid fa-book-open"></i></div><div class="report-kpi-label">Catalog books</div><div class="report-kpi-value"><?= (int)$stats['total_products'] ?></div></div>
  <div class="report-kpi"><div class="report-icon" style="background:#eafaf3;color:#159267"><i class="fa-solid fa-cubes-stacked"></i></div><div class="report-kpi-label">Stock units</div><div class="report-kpi-value"><?= (int)($inventory_summary['total_stock_units'] ?? 0) ?></div></div>
  <div class="report-kpi"><div class="report-icon" style="background:#fff4dc;color:#b77900"><i class="fa-solid fa-triangle-exclamation"></i></div><div class="report-kpi-label">Low stock</div><div class="report-kpi-value"><?= (int)$low_stock ?></div></div>
  <div class="report-kpi"><div class="report-icon" style="background:#f5edff;color:#7c3aed"><i class="fa-solid fa-user-group"></i></div><div class="report-kpi-label">Customers</div><div class="report-kpi-value"><?= (int)$stats['total_users'] ?></div></div>
</div>
<div class="report-grid">
  <section class="report-panel"><div class="report-panel-head"><div><div class="report-panel-title">Category breakdown</div><div class="report-panel-note">Book count by catalog category</div></div><i class="fa-solid fa-layer-group text-muted"></i></div><?php if(!empty($categories)): foreach($categories as $row): ?><div class="category-row"><div class="category-left"><span class="category-icon"><i class="fa-solid fa-book"></i></span><div><div class="category-name"><?= html_escape($row->pr_cate) ?></div><div class="category-count">Books in this category</div></div></div><strong><?= (int)$row->total_books ?></strong></div><?php endforeach; else: ?><div class="p-4 text-center text-muted small">No category data available.</div><?php endif; ?></section>
  <section class="report-panel"><div class="report-panel-head"><div><div class="report-panel-title">Store health</div><div class="report-panel-note">Signals that need admin attention</div></div><i class="fa-solid fa-shield-heart text-muted"></i></div><div class="health-box"><div class="health-line"><span>Out of stock</span><span class="health-status <?= $out_of_stock>0?'status-danger':'status-good' ?>"><?= (int)$out_of_stock ?></span></div><div class="health-line"><span>Low stock</span><span class="health-status <?= $low_stock>0?'status-warn':'status-good' ?>"><?= (int)$low_stock ?></span></div><div class="health-line"><span>eBooks</span><strong><?= (int)$inventory_summary['total_ebooks'] ?></strong></div><div class="health-line"><span>Orders</span><strong><?= (int)$stats['total_orders'] ?></strong></div><div class="health-line"><span>Completed payments</span><strong>₹<?= number_format((float)$stats['total_completed'],2) ?></strong></div></div></section>
</div>
<div class="report-foot"><div><strong>Admin summary</strong><div><span>Use Reports for decisions; manage individual records from the relevant sidebar page.</span></div></div><i class="fa-solid fa-arrow-trend-up" style="font-size:20px;opacity:.8"></i></div>