<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>BookSpot — Discover Your Next Read</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<link rel="stylesheet" href="<?= base_url('assets/css/style.css'); ?>">
<style>
.bs-page{background:#fff;color:#172033}.bs-line{height:1px;background:linear-gradient(90deg,transparent,#e7eaf0,transparent);margin:0 4%}.bs-promo{padding:58px 4%;background:#fff}.bs-promo-wrap{max-width:1320px;margin:auto;display:grid;grid-template-columns:1fr 1.35fr;gap:26px;align-items:stretch}.bs-promo-copy{padding:34px;border-radius:24px;background:linear-gradient(145deg,#f3f1ff,#fbfbff);border:1px solid #ebe7ff}.promo-chip{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border-radius:999px;background:#ece9ff;color:#5b4bdb;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.12em}.bs-promo-copy h2{font-size:33px;line-height:1.12;margin:14px 0 12px}.bs-promo-copy p{color:#6f7786;font-size:14px;line-height:1.75;margin:0}.promo-points{display:grid;gap:10px;margin-top:20px}.promo-point{display:flex;align-items:center;gap:10px;font-size:12px;color:#4f5b6d}.promo-point i{color:#5b4bdb}.bs-promo-img{overflow:hidden;border-radius:24px;min-height:270px}.bs-promo-img img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .6s}.bs-promo-img:hover img{transform:scale(1.03)}.bs-trust{padding:22px 4%;background:#fff}.bs-trust-wrap{max-width:1100px;margin:auto;display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.trust-item{display:flex;gap:11px;align-items:center;padding:15px;border:1px solid #eef0f4;border-radius:14px;background:#fff}.trust-icon{width:38px;height:38px;border-radius:11px;background:#f2efff;color:#6659da;display:grid;place-items:center}.trust-item strong{display:block;font-size:12px;color:#263247}.trust-item span{display:block;font-size:10px;color:#7a8391;margin-top:2px}@media(max-width:900px){.bs-promo-wrap{grid-template-columns:1fr}.bs-trust-wrap{grid-template-columns:1fr}}@media(max-width:560px){.bs-promo,.bs-trust{padding-left:5%;padding-right:5%}.bs-promo-copy h2{font-size:28px}}
</style>
<style id="bookspot-home-polish">
.bs-card-image{height:300px!important;object-fit:contain!important;padding:16px!important;background:#fbfbfd!important}
.bs-heart{width:44px!important;height:44px!important}
.bs-heart i,.bs-cart-btn i{font-size:20px!important}
.trust-icon{width:46px!important;height:46px!important}
</style>
<style id="bookspot-human-home-final">.bs-page{background:#f7f8fb}.bs-hero{padding-top:20px!important;background:#f7f8fb!important}.bs-hero-wrap{border:1px solid #e8eaf0;box-shadow:0 18px 50px rgba(27,35,53,.10)!important}.trust-item{box-shadow:0 6px 18px rgba(31,41,55,.035);transition:.2s}.trust-item:hover{transform:translateY(-2px);box-shadow:0 12px 25px rgba(31,41,55,.07)}.bs-cats{padding-top:64px!important;padding-bottom:64px!important}.cat-card{box-shadow:0 12px 30px rgba(31,41,55,.08)!important}.bs-book-section{padding-top:58px!important;padding-bottom:58px!important}.bs-card{flex-basis:260px!important;min-width:260px!important}.bs-card-box{height:390px!important;border-radius:14px!important;border-color:#e5e7eb!important;box-shadow:0 5px 16px rgba(31,41,55,.045)!important}.bs-card:hover .bs-card-box{box-shadow:0 16px 32px rgba(31,41,55,.11)!important}.bs-card-image{object-fit:contain!important;background:#f8f9fc!important;padding:18px!important}.bs-heart{width:44px!important;height:44px!important}.bs-cart-btn{min-height:44px!important;border-radius:11px!important;font-size:14px!important}.bs-promo{background:#f7f8fb!important;padding-top:64px!important;padding-bottom:64px!important}.bs-promo-copy,.bs-promo-img{border-radius:22px!important}.bs-promo-copy{box-shadow:0 12px 30px rgba(31,41,55,.05)}@media(max-width:800px){.bs-card{flex-basis:220px!important;min-width:220px!important}.bs-card-box{height:330px!important}}</style>
<div class="bs-page">
<?php $this->load->view('home/slider'); ?>
<div class="bs-trust"><div class="bs-trust-wrap"><div class="trust-item"><div class="trust-icon"><i class="fa-solid fa-shield-halved"></i></div><div><strong>Secure shopping</strong><span>Simple, reliable checkout experience.</span></div></div><div class="trust-item"><div class="trust-icon"><i class="fa-solid fa-truck-fast"></i></div><div><strong>Easy delivery</strong><span>Get books where you need them.</span></div></div><div class="trust-item"><div class="trust-icon"><i class="fa-solid fa-headset"></i></div><div><strong>Reader support</strong><span>We're here when you need help.</span></div></div></div></div>
<?php $this->load->view('home/categories'); ?>
<div class="bs-promo"><div class="bs-promo-wrap"><div class="bs-promo-copy"><div class="promo-chip"><i class="fa-solid fa-book-open-reader"></i> BookSpot picks</div><h2>Books for every season of your life.</h2><p>Build a shelf of stories that stay with you. Shop popular titles, explore new arrivals and keep your reading list moving.</p><div class="promo-points"><div class="promo-point"><i class="fa-solid fa-check"></i> Curated collections that are easy to browse</div><div class="promo-point"><i class="fa-solid fa-check"></i> Books to buy, rent or read digitally</div><div class="promo-point"><i class="fa-solid fa-check"></i> A clean experience from discovery to checkout</div></div></div><div class="bs-promo-img"><img src="<?= base_url('assets/uploads/Event_AllAges_GenericBookSale-2023.jpg'); ?>" alt="BookSpot promotion"></div></div></div>
<div id="new-arrivals"><?php $this->load->view('home/new_arrivals'); ?></div>
<?php $this->load->view('home/best_sellers'); ?>
<?php if (file_exists(APPPATH . 'views/about_contact.php')) { $this->load->view('about_contact'); } ?>
</div>
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script><script src="https://code.jquery.com/jquery-3.6.0.min.js"></script><script src="<?= base_url('assets/js/script.js'); ?>"></script>
<div id="rentPopup" class="popup-container" style="display:none"><div class="popup-box"><h2>Rent a Book</h2><form method="POST" id="rentForm" action="<?= site_url('rent'); ?>"><input type="hidden" name="user_id" value="<?= htmlspecialchars($user_id); ?>"><input type="hidden" id="hiddenProductId" name="product_id"><input type="hidden" id="hiddenProductName" name="product_name"><input type="hidden" id="hiddenProductImage" name="product_image"><label>Start Date:</label><input type="date" id="startDate" name="start_date" required onchange="calculateRent()"><label>End Date:</label><input type="date" id="endDate" name="end_date" required onchange="calculateRent()"><div class="rent-details"><p>Daily Rent: <b>₹19</b></p><p>Total Rent: <b>₹<span id="totalRent">0</span></b></p></div><input type="hidden" id="hiddenTotalRent" name="total_rent"><div class="terms-button-container"><label class="terms-label"><input type="checkbox" id="terms" required> I agree to the <a href="<?= base_url('assets/docs/520_B.I_ASSIGNMENT.pdf'); ?>" target="_blank">Terms &amp; Conditions</a></label><button type="submit" name="submit_rent" class="confirm-btn">Confirm Rent</button></div></form><button class="close-btn" onclick="closePopup()">Close</button></div></div>
<script>function openRentPopup(id,name,image){document.getElementById('hiddenProductId').value=id;document.getElementById('hiddenProductName').value=name;document.getElementById('hiddenProductImage').value=image;document.getElementById('rentPopup').style.display='flex'}function closePopup(){document.getElementById('rentPopup').style.display='none'}function calculateRent(){const s=document.getElementById('startDate').value,e=document.getElementById('endDate').value;if(s&&e){const a=new Date(s),b=new Date(e),d=Math.ceil((b-a)/86400000);if(d>0){const total=d*19;document.getElementById('totalRent').textContent=total;document.getElementById('hiddenTotalRent').value=total}else{alert('End date must be after start date!');document.getElementById('endDate').value=''}}}$(function(){$('.add-to-cart-form').on('submit',function(e){e.preventDefault();const form=$(this);$.ajax({url:'<?= site_url('cart/add'); ?>',type:'POST',data:form.serialize(),success:function(resp){let data;try{data=JSON.parse(resp)}catch(_){alert('Unexpected server response.');return}if(data.success){form.find('button').text('Added to Cart').prop('disabled',true);const c=document.getElementById('cartCount');if(c)c.textContent=data.cart_count||parseInt(c.textContent||'0',10)+1}else alert(data.message||'Could not add to cart.')}})})});</script>
