<style>
.bs-rent-section{padding:58px 4%;background:#f7f8fb;border-top:1px solid #edf0f4;border-bottom:1px solid #edf0f4}.bs-rent-wrap{max-width:1320px;margin:auto}.bs-rent-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.bs-rent-eyebrow{font-size:10px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;color:#8a91a0}.bs-rent-head h2{margin:6px 0 4px;font-size:30px;color:#172033;letter-spacing:-.03em}.bs-rent-head p{margin:0;color:#7a8391;font-size:13px}.bs-rent-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.bs-rent-card{background:#fff;border:1px solid #e6e9ef;border-radius:18px;padding:14px;display:grid;grid-template-columns:110px 1fr;gap:16px;position:relative;box-shadow:0 9px 24px rgba(31,41,55,.04)}.bs-rent-cover{width:110px;height:150px;border-radius:10px;background:#f3f4f8;display:grid;place-items:center;overflow:hidden}.bs-rent-cover img{width:100%;height:100%;object-fit:contain;padding:9px}.bs-rent-info{min-width:0}.bs-rent-wish{position:absolute;right:12px;top:12px;width:34px;height:34px;border:1px solid #e7e9ee;background:#fff;border-radius:50%;display:grid;place-items:center;color:#596275;cursor:pointer}.bs-rent-wish.is-wishlisted{color:#e4475a;background:#fff5f6;border-color:#f3c8ce}.bs-rent-title{margin:3px 44px 5px 0;font-size:15px;font-weight:800;color:#172033;line-height:1.35}.bs-rent-author{font-size:11px;color:#7b8492;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.bs-rent-price{margin-top:14px;font-size:15px;font-weight:800;color:#172033}.bs-rent-actions{display:flex;gap:8px;margin-top:12px}.bs-rent-btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;border-radius:9px;padding:9px 10px;font-size:10px;font-weight:800;text-decoration:none}.bs-rent-primary{background:#5b54ea;color:#fff;flex:1}.bs-rent-primary:hover{color:#fff;background:#4b44d1}.bs-rent-secondary{border:1px solid #e1e4ea;color:#4f5b6d;background:#fff}.bs-rent-secondary:hover{color:#172033;background:#f7f8fb}@media(max-width:1050px){.bs-rent-grid{grid-template-columns:1fr 1fr}}@media(max-width:700px){.bs-rent-grid{grid-template-columns:1fr}.bs-rent-head{align-items:flex-start;flex-direction:column}.bs-rent-head h2{font-size:26px}}
</style>
<section class="bs-rent-section"><div class="bs-rent-wrap">
  <div class="bs-rent-head"><div><div class="bs-rent-eyebrow">Read for a while</div><h2>Rent a book</h2><p>Choose a title, set your dates and enjoy it without keeping it on your shelf.</p></div><a class="bs-section-link" href="<?= site_url('category'); ?>">Browse all books <i class="fa-solid fa-arrow-right"></i></a></div>
  <div class="bs-rent-grid">
  <?php foreach ((array)$rent_picks as $product): $pid=(int)$product['id']; $wish=!empty($wishlistStatusRentPicks[$pid]); ?>
    <article class="bs-rent-card">
      <button class="bs-rent-wish wishlist-toggle <?= $wish?'is-wishlisted':''; ?>" type="button" data-product-id="<?= $pid; ?>" aria-label="<?= $wish?'Remove from wishlist':'Add to wishlist'; ?>" aria-pressed="<?= $wish?'true':'false'; ?>"><i class="<?= $wish?'fa-solid':'fa-regular'; ?> fa-heart"></i></button>
      <a class="bs-rent-cover" href="<?= site_url('product/details/'.$pid); ?>"><img src="<?= html_escape(product_image_url($product['image'])); ?>" alt="<?= html_escape($product['pr_name']); ?>" onerror="this.onerror=null;this.src='<?= base_url('assets/uploads/placeholder-book.svg'); ?>';"></a>
      <div class="bs-rent-info"><div class="bs-rent-title"><?= html_escape($product['pr_name']); ?></div><div class="bs-rent-author">by <?= html_escape($product['pr_author_name']); ?></div><div class="bs-rent-price">₹<?= number_format((float)$product['pr_price'],2); ?> / day</div><div class="bs-rent-actions"><a class="bs-rent-btn bs-rent-primary" href="<?= site_url('rent/'.$pid); ?>"><i class="fa-solid fa-book-open"></i> Rent</a><a class="bs-rent-btn bs-rent-secondary" href="<?= site_url('product/details/'.$pid); ?>" aria-label="View book"><i class="fa-regular fa-eye"></i></a></div></div>
    </article>
  <?php endforeach; ?>
  </div>
</div></section>
