<style>
.rent-page{padding:42px 22px 70px;background:#f7f7fb;min-height:calc(100vh - 120px)}
.rent-wrap{max-width:1100px;margin:auto}.rent-head{margin-bottom:24px}.rent-head small{font-weight:800;letter-spacing:.12em;color:#6657d9}.rent-head h1{margin:8px 0 6px;font-size:34px;color:#182033}.rent-head p{color:#6b7280;margin:0}
.rent-card{display:grid;grid-template-columns:360px 1fr;background:#fff;border:1px solid #e8eaf0;border-radius:22px;overflow:hidden;box-shadow:0 18px 50px rgba(20,24,40,.08)}
.rent-cover{background:#f0eff9;display:flex;align-items:center;justify-content:center;padding:36px;min-height:470px}.rent-cover img{width:100%;max-width:270px;height:370px;object-fit:contain;border-radius:10px;box-shadow:0 12px 28px rgba(0,0,0,.14)}
.rent-body{padding:40px}.rent-body h2{font-size:28px;color:#182033;margin:0 0 7px}.rent-author{color:#6b7280;margin-bottom:22px}.rent-author strong{color:#5b4bdb}.rent-price{font-size:26px;font-weight:800;color:#1f9d68;margin-bottom:24px}.rent-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.field label{display:block;font-size:12px;font-weight:750;color:#475467;margin-bottom:7px}.field input{width:100%;box-sizing:border-box;padding:13px 14px;border:1px solid #dfe2e8;border-radius:11px;background:#fff;font:inherit;outline:none}.field input:focus{border-color:#8c82ee;box-shadow:0 0 0 4px rgba(91,75,219,.08)}.rent-total{display:flex;justify-content:space-between;align-items:center;padding:16px;background:#f6f5ff;border-radius:13px;margin:22px 0;color:#475467}.rent-total strong{font-size:22px;color:#182033}.rent-actions{display:flex;gap:12px}.rent-btn{border:0;border-radius:12px;padding:14px 20px;font-weight:800;cursor:pointer;text-decoration:none;text-align:center}.rent-primary{background:#5b4bdb;color:#fff;flex:1}.rent-secondary{border:1px solid #dfe2e8;color:#475467;background:#fff}.rent-note{font-size:12px;color:#7b8493;margin-top:16px}
@media(max-width:800px){.rent-card{grid-template-columns:1fr}.rent-cover{min-height:360px}.rent-body{padding:28px}.rent-grid{grid-template-columns:1fr}}
</style>
<section class="rent-page"><div class="rent-wrap">
<div class="rent-head"><small>BOOK RENTAL</small><h1>Rent this book</h1><p>Choose your rental dates and see the total before confirming.</p></div>
<div class="rent-card">
<div class="rent-cover"><img src="<?= product_image_url($product['image']) ?>" alt="<?= html_escape($product['pr_name']) ?>"></div>
<div class="rent-body"><h2><?= html_escape($product['pr_name']) ?></h2><div class="rent-author">by <strong><?= html_escape($product['pr_author_name'] ?? 'BookSpot Author') ?></strong></div>
<div class="rent-price">₹<?= number_format((float)$product['pr_price'],2) ?> <span style="font-size:13px;font-weight:600;color:#7b8493">/ day</span></div>
<form method="post" action="<?= site_url('rent/save') ?>" id="rentForm"><input type="hidden" name="product_id" value="<?= (int)$product['id'] ?>"><input type="hidden" name="total_rent" id="total_rent">
<div class="rent-grid"><div class="field"><label>Start date</label><input type="date" name="start_date" id="start_date" required min="<?= date('Y-m-d') ?>"></div><div class="field"><label>End date</label><input type="date" name="end_date" id="end_date" required min="<?= date('Y-m-d') ?>"></div></div>
<div class="rent-total"><span>Rental total</span><strong id="rentTotal">₹0.00</strong></div>
<div class="rent-actions"><a class="rent-btn rent-secondary" href="<?= site_url('product/details/'.$product['id']) ?>">Back</a><button class="rent-btn rent-primary" type="submit">Confirm Rental</button></div>
<div class="rent-note"><i class="fa-solid fa-shield-halved"></i> Rental is added to your BookSpot cart. Review the dates and total before checkout.</div></form></div></div></div></section>
<script>
(function(){const price=<?= json_encode((float)$product['pr_price']) ?>,s=document.getElementById('start_date'),e=document.getElementById('end_date'),t=document.getElementById('rentTotal'),h=document.getElementById('total_rent');function calc(){if(!s.value||!e.value){t.textContent='₹0.00';h.value='0';return}const a=new Date(s.value+'T00:00:00'),b=new Date(e.value+'T00:00:00'),days=Math.max(1,Math.ceil((b-a)/86400000)+1),total=price*days;t.textContent='₹'+total.toFixed(2);h.value=total.toFixed(2)}s.addEventListener('change',function(){e.min=s.value;calc()});e.addEventListener('change',calc);document.getElementById('rentForm').addEventListener('submit',function(ev){if(!s.value||!e.value||e.value<s.value){ev.preventDefault();alert('Please select valid rental dates.')}})})();
</script>
