<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>BookSpot — Discover Your Next Read</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<link rel="stylesheet" href="<?= base_url('assets/css/style.css'); ?>">
<style>
.bs-page{background:#fff;color:#172033}.bs-line{height:1px;background:linear-gradient(90deg,transparent,#e7eaf0,transparent);margin:0 4%}.bs-promo{padding:58px 4%;background:#fff}.bs-promo-wrap{max-width:1320px;margin:auto;display:grid;grid-template-columns:1fr 1.35fr;gap:26px;align-items:stretch}.bs-promo-copy{padding:34px;border-radius:24px;background:linear-gradient(145deg,#f3f1ff,#fbfbff);border:1px solid #ebe7ff}.promo-chip{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border-radius:999px;background:#ece9ff;color:#5b4bdb;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.12em}.bs-promo-copy h2{font-size:33px;line-height:1.12;margin:14px 0 12px}.bs-promo-copy p{color:#6f7786;font-size:14px;line-height:1.75;margin:0}.promo-points{display:grid;gap:10px;margin-top:20px}.promo-point{display:flex;align-items:center;gap:10px;font-size:12px;color:#4f5b6d}.promo-point i{color:#5b4bdb}.bs-promo-img{overflow:hidden;border-radius:24px;min-height:270px}.bs-promo-img img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .6s}.bs-promo-img:hover img{transform:scale(1.03)}.bs-trust{padding:22px 4%;background:#fff}.bs-trust-wrap{max-width:1100px;margin:auto;display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.trust-item{display:flex;gap:11px;align-items:center;padding:15px;border:1px solid #eef0f4;border-radius:14px;background:#fff}.trust-icon{width:38px;height:38px;border-radius:11px;background:#f2efff;color:#6659da;display:grid;place-items:center}.trust-item strong{display:block;font-size:12px;color:#263247}.trust-item span{display:block;font-size:10px;color:#7a8391;margin-top:2px}@media(max-width:900px){.bs-promo-wrap{grid-template-columns:1fr}.bs-trust-wrap{grid-template-columns:1fr}}@media(max-width:560px){.bs-promo,.bs-trust{padding-left:5%;padding-right:5%}.bs-promo-copy h2{font-size:28px}}
</style>
<style id="bookspot-home-polish">
.bs-card-image{height:300px!important;object-fit:contain!important;padding:16px!important;background:#fbfbfd!important}
.bs-heart{width:44px!important;height:44px!important}
.bs-heart i,.bs-cart-btn i{font-size:20px!important}
.trust-icon{width:46px!important;height:46px!important}
</style>
<style id="bookspot-human-home-final">.bs-page{background:#f7f8fb}.bs-hero{padding-top:20px!important;background:#f7f8fb!important}.bs-hero-wrap{border:1px solid #e8eaf0;box-shadow:0 18px 50px rgba(27,35,53,.10)!important}.trust-item{box-shadow:0 6px 18px rgba(31,41,55,.035);transition:.2s}.trust-item:hover{transform:translateY(-2px);box-shadow:0 12px 25px rgba(31,41,55,.07)}.bs-cats{padding-top:64px!important;padding-bottom:64px!important}.cat-card{box-shadow:0 12px 30px rgba(31,41,55,.08)!important}.bs-book-section{padding-top:58px!important;padding-bottom:58px!important}.bs-card{flex-basis:260px!important;min-width:260px!important}.bs-card-box{height:390px!important;border-radius:14px!important;border-color:#e5e7eb!important;box-shadow:0 5px 16px rgba(31,41,55,.045)!important}.bs-card:hover .bs-card-box{box-shadow:0 16px 32px rgba(31,41,55,.11)!important}.bs-card-image{object-fit:contain!important;background:#f8f9fc!important;padding:18px!important}.bs-heart{width:44px!important;height:44px!important}.bs-cart-btn{min-height:44px!important;border-radius:11px!important;font-size:14px!important}.bs-promo{background:#f7f8fb!important;padding-top:64px!important;padding-bottom:64px!important}.bs-promo-copy,.bs-promo-img{border-radius:22px!important}.bs-promo-copy{box-shadow:0 12px 30px rgba(31,41,55,.05)}@media(max-width:800px){.bs-card{flex-basis:220px!important;min-width:220px!important}.bs-card-box{height:330px!important}}</style>
<div class="bs-page">
<?php $this->load->view('home/slider'); ?>
<div class="bs-trust"><div class="bs-trust-wrap"><div class="trust-item"><div class="trust-icon"><i class="fa-solid fa-shield-halved"></i></div><div><strong>Secure shopping</strong><span>Simple, reliable checkout experience.</span></div></div><div class="trust-item"><div class="trust-icon"><i class="fa-solid fa-truck-fast"></i></div><div><strong>Easy delivery</strong><span>Get books where you need them.</span></div></div><div class="trust-item"><div class="trust-icon"><i class="fa-solid fa-headset"></i></div><div><strong>Reader support</strong><span>We're here when you need help.</span></div></div></div></div>
<?php $this->load->view('home/categories'); ?>
<div class="bs-promo"><div class="bs-promo-wrap"><div class="bs-promo-copy"><div class="promo-chip"><i class="fa-solid fa-book-open-reader"></i> BookSpot picks</div><h2>Books for every season of your life.</h2><p>Build a shelf of stories that stay with you. Shop popular titles, explore new arrivals and keep your reading list moving.</p><div class="promo-points"><div class="promo-point"><i class="fa-solid fa-check"></i> Curated collections that are easy to browse</div><div class="promo-point"><i class="fa-solid fa-check"></i> Books to buy, rent or read digitally</div><div class="promo-point"><i class="fa-solid fa-check"></i> A clean experience from discovery to checkout</div></div></div><div class="bs-promo-img"><img src="<?= base_url('assets/uploads/Event_AllAges_GenericBookSale-2023.jpg'); ?>" alt="BookSpot promotion"></div></div></div>
<div id="new-arrivals"><?php $this->load->view('home/new_arrivals'); ?></div>
<?php $this->load->view('home/best_sellers'); ?>
<style id="bookspot-home-more-sections">
.bs-shelf{padding:64px 4%;background:#fff}.bs-shelf-wrap{max-width:1320px;margin:auto}.bs-section-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:22px}.bs-eyebrow{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.15em;color:#8a91a0}.bs-section-head h2{margin:5px 0 0;font-size:30px;letter-spacing:-.03em;color:#172033}.bs-section-head p{margin:7px 0 0;color:#7a8391;font-size:13px}.bs-section-link{font-size:12px;font-weight:800;color:#5b54ea;text-decoration:none;white-space:nowrap}.bs-format-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.bs-format{position:relative;overflow:hidden;min-height:160px;padding:22px;border-radius:18px;border:1px solid #eceef3;background:linear-gradient(145deg,#fff,#f8f9fc);text-decoration:none;color:#172033;transition:transform .2s,box-shadow .2s,border-color .2s}.bs-format:hover{transform:translateY(-4px);box-shadow:0 16px 32px rgba(26,34,50,.09);border-color:#dfe2ed;color:#172033}.bs-format-icon{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;background:#f0efff;color:#5b54ea;font-size:19px}.bs-format strong{display:block;font-size:16px;margin-top:18px}.bs-format span{display:block;font-size:11px;color:#7c8492;margin-top:5px;line-height:1.5}.bs-format .bs-format-arrow{position:absolute;right:18px;bottom:18px;color:#a0a6b2}
.bs-why{padding:66px 4%;background:#f7f8fb;border-top:1px solid #eef0f4;border-bottom:1px solid #eef0f4}.bs-why-wrap{max-width:1320px;margin:auto;display:grid;grid-template-columns:1.05fr 1.95fr;gap:30px;align-items:center}.bs-why-copy{padding-right:20px}.bs-why-copy h2{margin:8px 0 12px;font-size:32px;line-height:1.12;letter-spacing:-.03em;color:#172033}.bs-why-copy p{font-size:13px;line-height:1.8;color:#6f7786;max-width:520px}.bs-why-pills{display:flex;flex-wrap:wrap;gap:9px;margin-top:18px}.bs-why-pill{padding:8px 11px;border-radius:999px;background:#fff;border:1px solid #e9ebf1;font-size:10px;font-weight:700;color:#5d6778}.bs-benefits{display:grid;grid-template-columns:repeat(2,1fr);gap:13px}.bs-benefit{padding:18px;border-radius:17px;background:#fff;border:1px solid #e9edf2;box-shadow:0 8px 22px rgba(31,41,55,.035)}.bs-benefit-icon{width:40px;height:40px;border-radius:12px;background:#f1f0ff;color:#5b54ea;display:grid;place-items:center;font-size:17px}.bs-benefit strong{display:block;margin-top:12px;font-size:13px;color:#273248}.bs-benefit span{display:block;margin-top:5px;font-size:11px;line-height:1.65;color:#7b8492}
.bs-note{padding:58px 4%;background:#fff}.bs-note-wrap{max-width:1320px;margin:auto;border-radius:24px;padding:24px 26px;background:#111827;color:#fff;display:flex;align-items:center;justify-content:space-between;gap:25px}.bs-note-copy h3{margin:0;font-size:22px;letter-spacing:-.02em}.bs-note-copy p{margin:7px 0 0;color:#b8c1d1;font-size:12px;line-height:1.6}.bs-note-action{display:inline-flex;align-items:center;gap:8px;padding:12px 17px;background:#fff;color:#111827;border-radius:11px;text-decoration:none;font-size:12px;font-weight:800;white-space:nowrap}.bs-note-action:hover{color:#111827;background:#f0f2f6}
@media(max-width:1000px){.bs-format-grid{grid-template-columns:repeat(2,1fr)}.bs-why-wrap{grid-template-columns:1fr}.bs-why-copy{padding-right:0}.bs-note-wrap{align-items:flex-start;flex-direction:column}}
@media(max-width:560px){.bs-shelf,.bs-why,.bs-note{padding-left:5%;padding-right:5%}.bs-section-head{align-items:flex-start;flex-direction:column;gap:8px}.bs-section-head h2,.bs-why-copy h2{font-size:26px}.bs-format-grid,.bs-benefits{grid-template-columns:1fr}.bs-note-wrap{padding:22px}.bs-note-copy h3{font-size:19px}}
</style>

<section class="bs-shelf" id="browse-formats">
  <div class="bs-shelf-wrap">
    <div class="bs-section-head">
      <div><div class="bs-eyebrow">Browse your way</div><h2>Find the right reading shelf</h2><p>Explore books by the way you like to read, from quick picks to thoughtful long-form reads.</p></div>
      <a class="bs-section-link" href="<?= site_url('category'); ?>">Browse all categories <i class="fa-solid fa-arrow-right"></i></a>
    </div>
    <div class="bs-format-grid">
      <a class="bs-format" href="<?= site_url('category'); ?>"><span class="bs-format-icon"><i class="fa-solid fa-wand-magic-sparkles"></i></span><strong>Trending now</strong><span>Popular titles readers are discovering right now.</span><i class="bs-format-arrow fa-solid fa-arrow-right"></i></a>
      <a class="bs-format" href="<?= site_url('category'); ?>"><span class="bs-format-icon"><i class="fa-solid fa-brain"></i></span><strong>Self growth</strong><span>Practical books for habits, mindset and better work.</span><i class="bs-format-arrow fa-solid fa-arrow-right"></i></a>
      <a class="bs-format" href="<?= site_url('category'); ?>"><span class="bs-format-icon"><i class="fa-solid fa-feather-pointed"></i></span><strong>Stories &amp; fiction</strong><span>New worlds, unforgettable characters and page-turners.</span><i class="bs-format-arrow fa-solid fa-arrow-right"></i></a>
      <a class="bs-format" href="<?= site_url('category'); ?>"><span class="bs-format-icon"><i class="fa-solid fa-graduation-cap"></i></span><strong>Study &amp; learning</strong><span>Useful reads for students, skills and lifelong learning.</span><i class="bs-format-arrow fa-solid fa-arrow-right"></i></a>
    </div>
  </div>
</section>

<section class="bs-why">
  <div class="bs-why-wrap">
    <div class="bs-why-copy">
      <div class="bs-eyebrow">Made for readers</div>
      <h2>A smoother way to discover your next book.</h2>
      <p>BookSpot keeps browsing simple: clear collections, useful details and a shopping flow that gets out of your way so you can spend more time choosing what to read.</p>
      <div class="bs-why-pills"><span class="bs-why-pill">Easy browsing</span><span class="bs-why-pill">Secure checkout</span><span class="bs-why-pill">Reader-friendly layout</span><span class="bs-why-pill">Buy or rent</span></div>
    </div>
    <div class="bs-benefits">
      <div class="bs-benefit"><div class="bs-benefit-icon"><i class="fa-solid fa-magnifying-glass"></i></div><strong>Discover faster</strong><span>Use categories, collections and search to get to the right title without extra clicks.</span></div>
      <div class="bs-benefit"><div class="bs-benefit-icon"><i class="fa-solid fa-heart"></i></div><strong>Keep a wishlist</strong><span>Save books you like and come back to them when you're ready.</span></div>
      <div class="bs-benefit"><div class="bs-benefit-icon"><i class="fa-solid fa-bag-shopping"></i></div><strong>Simple cart</strong><span>Add books quickly, adjust quantities and move straight to checkout.</span></div>
      <div class="bs-benefit"><div class="bs-benefit-icon"><i class="fa-solid fa-repeat"></i></div><strong>Flexible reading</strong><span>Choose purchase or rental flows where available for a more flexible shelf.</span></div>
    </div>
  </div>
</section>

<section class="bs-note">
  <div class="bs-note-wrap">
    <div class="bs-note-copy"><h3>Still deciding what to read?</h3><p>Start with our latest arrivals and bestselling picks, then build your next stack one book at a time.</p></div>
    <a class="bs-note-action" href="#new-arrivals"><i class="fa-solid fa-book-open-reader"></i> Explore new arrivals</a>
  </div>
</section>

<?php if (file_exists(APPPATH . 'views/about_contact.php')) { $this->load->view('about_contact'); } ?>
</div>
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script><script src="https://code.jquery.com/jquery-3.6.0.min.js"></script><script src="<?= base_url('assets/js/script.js'); ?>"></script>
<div id="rentPopup" class="popup-container" style="display:none"><div class="popup-box"><h2>Rent a Book</h2><form method="POST" id="rentForm" action="<?= site_url('rent'); ?>"><input type="hidden" name="user_id" value="<?= htmlspecialchars($user_id); ?>"><input type="hidden" id="hiddenProductId" name="product_id"><input type="hidden" id="hiddenProductName" name="product_name"><input type="hidden" id="hiddenProductImage" name="product_image"><label>Start Date:</label><input type="date" id="startDate" name="start_date" required onchange="calculateRent()"><label>End Date:</label><input type="date" id="endDate" name="end_date" required onchange="calculateRent()"><div class="rent-details"><p>Daily Rent: <b>₹19</b></p><p>Total Rent: <b>₹<span id="totalRent">0</span></b></p></div><input type="hidden" id="hiddenTotalRent" name="total_rent"><div class="terms-button-container"><label class="terms-label"><input type="checkbox" id="terms" required> I agree to the <a href="<?= base_url('assets/docs/520_B.I_ASSIGNMENT.pdf'); ?>" target="_blank">Terms &amp; Conditions</a></label><button type="submit" name="submit_rent" class="confirm-btn">Confirm Rent</button></div></form><button class="close-btn" onclick="closePopup()">Close</button></div></div>
<script>function openRentPopup(id,name,image){document.getElementById('hiddenProductId').value=id;document.getElementById('hiddenProductName').value=name;document.getElementById('hiddenProductImage').value=image;document.getElementById('rentPopup').style.display='flex'}function closePopup(){document.getElementById('rentPopup').style.display='none'}function calculateRent(){const s=document.getElementById('startDate').value,e=document.getElementById('endDate').value;if(s&&e){const a=new Date(s),b=new Date(e),d=Math.ceil((b-a)/86400000);if(d>0){const total=d*19;document.getElementById('totalRent').textContent=total;document.getElementById('hiddenTotalRent').value=total}else{alert('End date must be after start date!');document.getElementById('endDate').value=''}}}$(function(){$('.add-to-cart-form').on('submit',function(e){e.preventDefault();const form=$(this);$.ajax({url:'<?= site_url('cart/add'); ?>',type:'POST',data:form.serialize(),success:function(resp){let data;try{data=JSON.parse(resp)}catch(_){alert('Unexpected server response.');return}if(data.success){const btn=form.find('button'); btn.replaceWith('<a class="bs-cart-btn bs-go-cart" href="<?= site_url('cart'); ?>"><i class="fa-solid fa-bag-shopping"></i> Go To Cart</a>');const c=document.getElementById('cartCount');if(c)c.textContent=data.cart_count||parseInt(c.textContent||'0',10)+1}else alert(data.message||'Could not add to cart.')}})})});</script>
