<style>
.wl-page{background:#f7f8fb;min-height:calc(100vh - 150px);padding:42px 4% 70px;font-family:Inter,system-ui,sans-serif}.wl-wrap{max-width:1320px;margin:auto}.wl-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:24px}.wl-head h1{margin:0;color:#172033;font-size:32px;letter-spacing:-.03em}.wl-head p{margin:8px 0 0;color:#7b8492;font-size:13px}.wl-clear{display:inline-flex;align-items:center;gap:8px;text-decoration:none;color:#d84652;font-size:12px;font-weight:800;padding:10px 13px;border:1px solid #f1c7cc;border-radius:10px;background:#fff}.wl-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:22px}.wl-card{background:#fff;border:1px solid #e8eaf0;border-radius:16px;padding:14px;box-shadow:0 7px 22px rgba(27,35,53,.045);position:relative}.wl-cover{height:300px;border-radius:11px;background:#f5f6f9;display:grid;place-items:center;overflow:hidden}.wl-cover img{width:100%;height:100%;object-fit:contain;padding:14px}.wl-remove{position:absolute;right:22px;top:22px;width:38px;height:38px;border-radius:50%;border:1px solid #eceef3;background:#fff;color:#d74b5c;display:grid;place-items:center;text-decoration:none;box-shadow:0 5px 14px rgba(0,0,0,.08)}.wl-name{margin:15px 0 4px;font-size:15px;font-weight:800;color:#172033;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.wl-author{font-size:12px;color:#7b8492}.wl-bottom{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:13px}.wl-price{font-size:17px;font-weight:850;color:#172033}.wl-cart{display:inline-flex;align-items:center;gap:7px;text-decoration:none;background:#e4474c;color:#fff;border-radius:9px;padding:10px 12px;font-size:11px;font-weight:800}.wl-cart:hover{color:#fff;background:#cf373d}.wl-empty{background:#fff;border:1px solid #e8eaf0;border-radius:18px;padding:70px 20px;text-align:center}.wl-empty-icon{width:72px;height:72px;border-radius:22px;background:#f0efff;color:#5b54ea;display:grid;place-items:center;font-size:28px;margin:0 auto 18px}.wl-empty h2{margin:0;color:#172033;font-size:24px}.wl-empty p{color:#7b8492;font-size:13px;margin:8px auto 20px;max-width:460px}.wl-shop{display:inline-flex;align-items:center;gap:8px;background:#5b54ea;color:#fff;text-decoration:none;border-radius:10px;padding:11px 16px;font-size:12px;font-weight:800}.wl-shop:hover{color:#fff;background:#4d46d0}@media(max-width:1050px){.wl-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:760px){.wl-head{align-items:flex-start;flex-direction:column}.wl-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.wl-cover{height:250px}}@media(max-width:460px){.wl-page{padding-left:5%;padding-right:5%}.wl-grid{grid-template-columns:1fr 1fr;gap:12px}.wl-card{padding:10px}.wl-cover{height:205px}.wl-name{font-size:13px}.wl-bottom{align-items:flex-start;flex-direction:column}.wl-cart{width:100%;justify-content:center;box-sizing:border-box}}
</style>
<div class="wl-page"><div class="wl-wrap">
  <div class="wl-head"><div><h1>My Wishlist</h1><p><?= (int)$wishlistCount ?> book<?= ((int)$wishlistCount===1?'':'s') ?> saved for later.</p></div><?php if(!empty($products)): ?><a class="wl-clear" href="<?= site_url('wishlist/clear'); ?>" onclick="return confirm('Clear your wishlist?');"><i class="fa-solid fa-trash-can"></i> Clear Wishlist</a><?php endif; ?></div>
  <?php if(empty($products)): ?>
    <div class="wl-empty"><div class="wl-empty-icon"><i class="fa-solid fa-heart"></i></div><h2>Your wishlist is empty</h2><p>Tap the heart on any book card to save it here and build your next reading list.</p><a class="wl-shop" href="<?= site_url('category'); ?>"><i class="fa-solid fa-book-open"></i> Explore Books</a></div>
  <?php else: ?>
    <div class="wl-grid">
      <?php foreach($products as $product): ?>
        <article class="wl-card">
          <a class="wl-remove" href="<?= site_url('wishlist/remove/'.$product['id']); ?>" title="Remove from wishlist"><i class="fa-solid fa-xmark"></i></a>
          <a href="<?= site_url('product/details/'.$product['id']); ?>" class="wl-cover"><img src="<?= html_escape(product_image_url($product['image'])); ?>" alt="<?= html_escape($product['pr_name']); ?>" onerror="this.onerror=null;this.src='<?= base_url('assets/uploads/placeholder-book.svg'); ?>';"></a>
          <a href="<?= site_url('product/details/'.$product['id']); ?>" style="text-decoration:none"><div class="wl-name"><?= html_escape($product['pr_name']); ?></div></a>
          <div class="wl-author">by <?= html_escape($product['pr_author_name']); ?></div>
          <div class="wl-bottom"><span class="wl-price">₹ <?= number_format((float)$product['pr_price'],2); ?></span><a class="wl-cart" href="<?= site_url('product/details/'.$product['id']); ?>"><i class="fa-solid fa-bag-shopping"></i> View Book</a></div>
        </article>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>
</div></div>
