<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Cart_model extends CI_Model {
 public function get_items($user_id){$q=[];$params=[];if($this->db->table_exists('add_to_cart')&&$this->db->table_exists('products')){$q[]="SELECT c.id,c.product_id,p.pr_name AS name,p.image AS image,p.pr_price AS price,c.quantity,NULL AS start_date,NULL AS end_date,'cart' AS item_type FROM add_to_cart c JOIN products p ON c.product_id=p.id WHERE c.user_id=?";$params[]=$user_id;}if($this->db->table_exists('rent')){$q[]="SELECT r.id,NULL AS product_id,r.book_name AS name,r.book_image AS image,r.total_rent AS price,1 AS quantity,r.start_date,r.end_date,'rent' AS item_type FROM rent r WHERE r.user_id=?";$params[]=$user_id;}if(!$q)return [];return $this->db->query(implode(' UNION ALL ',$q).' ORDER BY name ASC',$params)->result_array();}
 public function get_cart_count($user_id){$n=0;if($this->db->table_exists('add_to_cart')){$r=$this->db->select_sum('quantity')->where('user_id',$user_id)->get('add_to_cart')->row();$n+=($r&&$r->quantity)?(int)$r->quantity:0;}if($this->db->table_exists('rent'))$n+=(int)$this->db->where('user_id',$user_id)->count_all_results('rent');return $n;}
 public function add_item($user_id,$product_id,$quantity=1){if(!$this->db->table_exists('add_to_cart'))return false;$quantity=max(1,(int)$quantity);$r=$this->db->where('user_id',$user_id)->where('product_id',$product_id)->get('add_to_cart')->row_array();if($r)return $this->db->where('id',$r['id'])->where('user_id',$user_id)->update('add_to_cart',['quantity'=>(int)$r['quantity']+$quantity]);return $this->db->insert('add_to_cart',['user_id'=>$user_id,'product_id'=>$product_id,'quantity'=>$quantity]);}
 public function get_item_quantity($user_id,$id){if(!$this->db->table_exists('add_to_cart'))return 1;$r=$this->db->select('quantity')->where('id',$id)->where('user_id',$user_id)->get('add_to_cart')->row_array();return $r?(int)$r['quantity']:1;}
 public function update_quantity($user_id,$id,$quantity){if(!$this->db->table_exists('add_to_cart'))return false;return $this->db->where('id',$id)->where('user_id',$user_id)->update('add_to_cart',['quantity'=>max(1,(int)$quantity)]);}
 public function clear_items($user_id){if($this->db->table_exists('add_to_cart'))$this->db->where('user_id',$user_id)->delete('add_to_cart');if($this->db->table_exists('rent'))$this->db->where('user_id',$user_id)->delete('rent');return true;}
 public function remove_item($user_id,$id,$type){if($type==='rent')return $this->db->table_exists('rent')?$this->db->where('id',$id)->where('user_id',$user_id)->delete('rent'):false;return $this->db->table_exists('add_to_cart')?$this->db->where('id',$id)->where('user_id',$user_id)->delete('add_to_cart'):false;}
}
